feat(core): deny no json header access
codemateDao/codemate-core pull request #1
Opened 2024-04-04 15:16 UTC by StupidQu

feat(core): deny no json header access

Deny request when a user without super admin accessing @hydrooj/ui-default pages.

2024-04-04 15:18 UTC, StupidQu commented
需要说明的是，带有副作用的操作仍会被执行。即：如果一个用户请求提交了一份代码以评测，这个评测任务仍会被执行，只是不返回数据。

2024-04-05 13:55 UTC, KiritoKing requested changes

2024-04-05 13:55 UTC, KiritoKing commented on packages/hydrooj/src/service/layers/response.ts
> +        if (!user.hasPriv(PRIV.PRIV_EDIT_SYSTEM) && !request.json) {
改成throw 403 forbidden吧 这样看起来不像挂了

2024-04-05 15:18 UTC, KiritoKing commented
ok 没问题了 非常好
> 为后续人员说明：
> 这里强制要求`accpet: application/json`是为了避免post请求出现302 redirect的情况

2024-04-05 15:21 UTC, merged